# Generated by Cursor on 2026-03-12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="stock",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="subcategory",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="publication_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="pages",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.CharField(default="Vietnamese", max_length=50),
        ),
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="average_rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="book",
            name="review_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="book",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="book",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="book",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]

